# 配置文件示例

# 数据库相关配置
[database]
# 数据库驱动名称：对于MySQL数据库，填"mysql"；对于SQLServer数据库，填"sqlserver"
driver = "mysql"

# dsn(DataSourceName)，即数据源，填写格式如下：
#
# 对于mysql，"username:password@protocol(address)/dbname?param1=value1&...&paramN=valueN"
# 具体详情请参考：https://github.com/go-sql-driver/mysql?tab=readme-ov-file#dsn-data-source-name
#
# 对于sqlserver，"sqlserver://username:password@host/instance?param1=value&param2=value"
# 具体详情参考：https://github.com/denisenkom/go-mssqldb?tab=readme-ov-file#connection-parameters-and-dsn
dsn = "admin:12345678@tcp(127.0.0.1:3306)/minimark"

# 服务器相关配置
[server]
ip = "0.0.0.0"
port = 8080
# 配置管理员用户，可以配置多个
users = [
    {username="admin", password="12345678"},
    {username="root", password="123456789"}
]

# 安全性相关配置
[security]
# jwt加密密钥
jwt_key = "qwertyasdfgh"
# 登录信息过期时间，单位为秒
jwt_expire = 86400